fix husky scripts

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -3,7 +3,7 @@
 
 message="$(cat $1)"
 requiredPattern="^(add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge) .*$"
-if ! [[ $message =~ $requiredPattern ]];
+if ! echo "$message" | grep -qE "$requiredPattern";
 then
   echo "-"
   echo "-"
@@ -20,4 +20,4 @@ then
   echo "For more information, check script in .husky/commit-msg"
   echo "-"
   exit 1
-fiundefined
+fi
